# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sonlt373/Desktop/SoNg/AI_cam_tracking/dev/sort-yolov5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sonlt373/Desktop/SoNg/AI_cam_tracking/dev/sort-yolov5

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sonlt373/Desktop/SoNg/AI_cam_tracking/dev/sort-yolov5/CMakeFiles /home/sonlt373/Desktop/SoNg/AI_cam_tracking/dev/sort-yolov5//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sonlt373/Desktop/SoNg/AI_cam_tracking/dev/sort-yolov5/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sort

# Build rule for target.
sort: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sort
.PHONY : sort

# fast build rule for target.
sort/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/build
.PHONY : sort/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/main.cpp.s
.PHONY : main.cpp.s

source/hungarian.o: source/hungarian.cpp.o
.PHONY : source/hungarian.o

# target to build an object file
source/hungarian.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/source/hungarian.cpp.o
.PHONY : source/hungarian.cpp.o

source/hungarian.i: source/hungarian.cpp.i
.PHONY : source/hungarian.i

# target to preprocess a source file
source/hungarian.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/source/hungarian.cpp.i
.PHONY : source/hungarian.cpp.i

source/hungarian.s: source/hungarian.cpp.s
.PHONY : source/hungarian.s

# target to generate assembly for a file
source/hungarian.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/source/hungarian.cpp.s
.PHONY : source/hungarian.cpp.s

source/kalmanboxtracker.o: source/kalmanboxtracker.cpp.o
.PHONY : source/kalmanboxtracker.o

# target to build an object file
source/kalmanboxtracker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/source/kalmanboxtracker.cpp.o
.PHONY : source/kalmanboxtracker.cpp.o

source/kalmanboxtracker.i: source/kalmanboxtracker.cpp.i
.PHONY : source/kalmanboxtracker.i

# target to preprocess a source file
source/kalmanboxtracker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/source/kalmanboxtracker.cpp.i
.PHONY : source/kalmanboxtracker.cpp.i

source/kalmanboxtracker.s: source/kalmanboxtracker.cpp.s
.PHONY : source/kalmanboxtracker.s

# target to generate assembly for a file
source/kalmanboxtracker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/source/kalmanboxtracker.cpp.s
.PHONY : source/kalmanboxtracker.cpp.s

source/sort.o: source/sort.cpp.o
.PHONY : source/sort.o

# target to build an object file
source/sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/source/sort.cpp.o
.PHONY : source/sort.cpp.o

source/sort.i: source/sort.cpp.i
.PHONY : source/sort.i

# target to preprocess a source file
source/sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/source/sort.cpp.i
.PHONY : source/sort.cpp.i

source/sort.s: source/sort.cpp.s
.PHONY : source/sort.s

# target to generate assembly for a file
source/sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/source/sort.cpp.s
.PHONY : source/sort.cpp.s

source/utils.o: source/utils.cpp.o
.PHONY : source/utils.o

# target to build an object file
source/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/source/utils.cpp.o
.PHONY : source/utils.cpp.o

source/utils.i: source/utils.cpp.i
.PHONY : source/utils.i

# target to preprocess a source file
source/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/source/utils.cpp.i
.PHONY : source/utils.cpp.i

source/utils.s: source/utils.cpp.s
.PHONY : source/utils.s

# target to generate assembly for a file
source/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/source/utils.cpp.s
.PHONY : source/utils.cpp.s

source/yolov5.o: source/yolov5.cpp.o
.PHONY : source/yolov5.o

# target to build an object file
source/yolov5.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/source/yolov5.cpp.o
.PHONY : source/yolov5.cpp.o

source/yolov5.i: source/yolov5.cpp.i
.PHONY : source/yolov5.i

# target to preprocess a source file
source/yolov5.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/source/yolov5.cpp.i
.PHONY : source/yolov5.cpp.i

source/yolov5.s: source/yolov5.cpp.s
.PHONY : source/yolov5.s

# target to generate assembly for a file
source/yolov5.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/source/yolov5.cpp.s
.PHONY : source/yolov5.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sort"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... source/hungarian.o"
	@echo "... source/hungarian.i"
	@echo "... source/hungarian.s"
	@echo "... source/kalmanboxtracker.o"
	@echo "... source/kalmanboxtracker.i"
	@echo "... source/kalmanboxtracker.s"
	@echo "... source/sort.o"
	@echo "... source/sort.i"
	@echo "... source/sort.s"
	@echo "... source/utils.o"
	@echo "... source/utils.i"
	@echo "... source/utils.s"
	@echo "... source/yolov5.o"
	@echo "... source/yolov5.i"
	@echo "... source/yolov5.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

